### ISSUE TITLE
Quiero más de todo

### ISSUE THREAD

**Issue by ibisshagrat** [nicoProbrando/Vengadores#5]
Trabajo duro y con generosa gratificación moral.

**Comment by ibisshagrat** [comment]
Esto está relacionado con #2

**Comment by R3pl1k4nt3** [comment]
Es lunes por la mañana!! Que afán trabajador 
![burla](https://user-images.githubusercontent.com/70742653/104892061-03cf6780-5972-11eb-8344-542084eb10eb.jpg)

**Comment by ibisshagrat** [comment]
Me pongo a ello
